---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Deployment for status-page-exporter
  labels:
    app: status-page-exporter
    app.kubernetes.io/component: status-page-exporter
    app.kubernetes.io/instance: status-page-exporter
    app.kubernetes.io/name: status-page-exporter
    app.kubernetes.io/part-of: status-page-exporter
  name: status-page-exporter
  # namespace: <++>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status-page-exporter
  template:
    metadata:
      labels:
        app: status-page-exporter
    spec:
      containers:
      - name: status-page-exporter
        # TODO: replace with image name
        image: status-page-exporter
        imagePullPolicy: Always
        # TODO: envFrom Secret
        env:
          - name: PAGE_ID
            value: foo
          - name: TOKEN
            value: bar
        ports:
        - containerPort: 9101
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Service for exporter
  labels:
    app: exporter
    app.kubernetes.io/component: exporter
    app.kubernetes.io/instance: exporter
    app.kubernetes.io/name: exporter
    app.kubernetes.io/part-of: exporter
  name: exporter
  # namespace: <++>
spec:
  ports:
  - name: exporter
    port: 9101
    protocol: TCP
    targetPort: 9101
  selector:
    app: exporter
  sessionAffinity: None
  type: ClusterIP

